version: "3.9"
   
services:
  db:
    image: postgres
    user: postgres
    volumes:
      - ./sql/install.sql:/docker-entrypoint-initdb.d/install.sql
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
        test: ["CMD-SHELL", "pg_isready"] 
        interval: 10s
        timeout: 5s
        retries: 5
  web:
    build: .
    command: python -m server
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
